### ISSUE TITLE
add 'Type-Driven Development with Idris' to bibliography

### ISSUE THREAD

**Issue by gdmcbain** [jozefg/learn-tt#6]
I've only read chapter 1 'Overview' thus far of Edwin Brady's (2017) book [Type-driven Development with Idris](https://www.manning.com/books/type-driven-development-with-idris), but found it to be a very readable introduction to what programming with types front of mind might be like.  Perhaps it merits inclusion in the list.

**Comment by jozefg** [comment]
OK, I've finished most of the book at this point and agree! It should absolutely be added. Now I just need to remember to do so...
